[package]
name = "pab-platform"
version = "1.2.29"
edition.workspace = true
rust-version.workspace = true

[dependencies]
blake3 = "1"
os_info = { version = "=3.15.0", default-features = false }
pab-protocol = { path = "../protocol" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo = { version = "=0.39.6", default-features = false, features = ["system", "disk", "network", "user"] }
nvml-wrapper = "=0.13.0"

netstat2 = "=0.11.2"
hickory-resolver = { version = "=0.26.3", default-features = false, features = ["tokio", "system-config"] }
tokio.workspace = true
pab-os-sessions = { path = "../os-sessions" }

pab-os-control = { path = "../os-control" }

[dev-dependencies]
pab-task-runtime = { path = "../task-runtime" }
