import { test, expect } from '@playwright/test';

test('real registration, refresh, device list, preferences, password and logout', async ({ page }) => {
  const username = `browser-${Date.now()}`;
  await page.goto('/');
  await page.getByRole('button', { name: 'Create an account', exact: true }).click();
  await page.getByLabel('Username', { exact: true }).fill(username);
  await page.getByLabel('Password', { exact: true }).fill('test password long enough');
  await page.getByLabel('Confirm password', { exact: true }).fill('test password long enough');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
  await page.getByRole('menuitem', { name: 'My devices', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'My devices', exact: true })).toBeVisible();
  await expect(page.getByText('No data', { exact: true })).toBeVisible();
  await expect(page.getByRole('menuitem', { name: 'My devices', exact: true })).toHaveCount(1);
  await expect(page.getByRole('menuitem', { name: 'All devices', exact: true })).toHaveCount(0);
  expect((await page.request.get('/api/web/devices?scope=all')).status()).toBe(403);
  await page.getByRole('button', { name: 'Dark', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.getByRole('menuitem', { name: 'My account', exact: true }).click();
  await page.getByLabel('Current password', { exact: true }).fill('wrong password');
  await page.getByLabel('New password', { exact: true }).fill('updated password long enough');
  await page.getByLabel('Confirm password', { exact: true }).fill('updated password long enough');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByText('The current password is incorrect.', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'My account', exact: true })).toBeVisible();
  await page.getByLabel('Current password', { exact: true }).fill('test password long enough');
  await page.getByLabel('New password', { exact: true }).fill('updated password long enough');
  await page.getByLabel('Confirm password', { exact: true }).fill('updated password long enough');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByText('Password updated.', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toBeVisible();
  await page.getByLabel('Username', { exact: true }).fill(username);
  await page.getByLabel('Password', { exact: true }).fill('updated password long enough');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toBeVisible();
});
