[package]
name = "pab-os-control"
version = "1.2.9"
edition.workspace = true
rust-version.workspace = true

[dependencies]
pab-protocol = { path = "../protocol" }
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
windows-service = "=0.8.1"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_System_Services", "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader"] }

[target.'cfg(target_os = "linux")'.dependencies]
futures-util = "0.3"
rustix = { version = "=1.1.4", features = ["process", "event"] }
zbus_systemd = { version = "=0.26100.0", default-features = false, features = ["systemd1", "zbus-async-tokio"] }

[dev-dependencies]
tempfile = "3"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
plist = "1"
